### Boolean mask

In [7]:
import numpy as np
import pandas as pd
from numpy.random import default_rng

In [8]:
rg = default_rng(12345)
random_integers = rg.integers(low=1, high=5, size = 100)

In [9]:
random_integers[:5]

array([3, 1, 4, 2, 1])

In [10]:
equal_3 = random_integers == 3

In [11]:
equal_3[:5]

array([ True, False, False, False, False])

In [12]:
sum(equal_3)

31

In [13]:
random_integers[equal_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3])